# This is a basic workflow to help you get started with Actions

name: dispatch_test

env:
      KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TARGET_DAGS_DIR: ${{ secrets.DAGS_DIR }}
      SOURCE_DAGS_DIR: dags
      S3_BUCKET_NAME: andydagsbucket
      
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ dispatch ]
#  pull_request:
#    branches: [ dispatch ]

  workflow_dispatch:
    inputs:
      runnerName:
        description: 'Runner name'
        required: true
        default: 'Andy'
        type: choice
        options:
        - Kryvokon
        - Andy
        - Chernyshev

jobs:
  checkout_and_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
       
      - name: Run some linux command
        run: |
          echo "Runner name : $RNAME"
          echo "Runner name : ANDY REZNICHENKO"
          hostname
          hostname -i
          echo "Trying to connect to AWS"
          aws s3 --help
        env:
          RNAME: ${{ inputs.runnerName }}
          
      - name: Output bucket content
        run: |
          echo "I'm in $(pwd) directory"
          cd $SOURCE_DAGS_DIR || (echo "Could not change directory on dags" && exit 1)
          #cd dags || (echo "Could not change directory on dags" && exit 1)
          echo "S3_BUCKET_NAME: $S3_BUCKET_NAME"
          aws s3 sync . s3://${S3_BUCKET_NAME}/${TARGET_DAGS_DIR}/ --size-only

      - name: List bucket content
        run: |
          aws s3 ls s3://$S3_BUCKET_NAME --recursive | awk '{$1=$2=$3=""; print $0}' | sed 's/^[ \t]*//'
