# This is a basic workflow to help you get started with Actions

name: dispatch_test

env:
      KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DAGS: ${{ secrets.DAGS_DIR }}
      
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ dispatch ]
#  pull_request:
#    branches: [ dispatch ]

  workflow_dispatch:
    inputs:
      runnerName:
        description: 'Runner name'
        required: true
        default: 'Andy'
        type: choice
        options:
        - Kryvokon
        - Andy
        - Chernyshev

jobs:
  checkout_and_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
       
      - name: Run some linux command
        run: |
          echo "Runner name : $RNAME"
          echo "Runner name : ANDY REZNICHENKO"
          hostname
          hostname -i
          echo "Trying to connect to AWS"
          aws s3 --help
        env:
          RNAME: ${{ inputs.runnerName }}
          
      - name: Output bucket content
        run: |
          echo "I'm in $(pwd) directory"
          export AWS_ACCESS_KEY_ID=$KEY_ID
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          export AWS_SECRET_ACCESS_KEY=$ACCESS_KEY
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          export AWS_DEFAULT_REGION=eu-central-1
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
          aws s3 ls
          aws s3 sync dags/ s3://andydagsbucket/$DAGS/
