name: out_example

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      runnerName:
        description: 'Runner name'
        required: true
        default: 'Andy'
        type: choice
        options:
        - Kryvokon
        - Andy
        - Chernyshev

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello andy and" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world best ever" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
